[package]
name = "lazyfs"
version = "0.1.0"
authors = ["David Roundy <roundyd@physics.oregonstate.edu>"]

description = "a package for 'lazy' versions of fs functins"
license = "BSD-2-Clause"
repository = "https://github.com/droundy/lazyfs"

